[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
  let g:coc_disable_startup_warning = 1
  command! -nargs=0 Prettier :CocCommand prettier.formatFile
'''
